"{\
  'general':\
  {\
    'name':'Device',\
    'instance':1,\
    'interval':5000,\
    'print_verbosity':2\
  },\
  'components':[\
    {\
      'name':'Analog',\
      'params':'default'\
    },\
    {\
      'name':'SD',\
      'params': [true,1000,10,'dend',true]\
    },\
    {\
      'name':'DS3231',\
      'params':'default'\
    }\
  ]\
}"
